config/routes.rb
Rails.application.routes.draw do


  resources :articles
  resources :vendors
  resources :products
  resources :collars
  resources :screenings
  resources :trinkets do
    resources :comments
  end
  resources :dogs
  resources :critters
  devise_for :users, :controllers => {:registrations => "registrations"}

  resources :users, only: [:show], as: :user

  root 'pages#home'
  get 'about', to: 'pages#about', as: :about
  get 'lipsum', to: 'pages#lipsum', as: :lipsum
  get 'scopes', to: 'pages#scopes', as: :scopes
  get 'framer', to: 'pages#framer', as: :framer
  get 'framer2', to: 'pages#framer2', as: :framer2
  get 'context', to: 'pages#context', as: :context
  get 'paver', to: 'pages#paver', as: :paver
  get 'filter', to: 'pages#filter', as: :filter
  get 'gimmie_crits', to: 'pages#gimmie_crits', as: :gimmie_crits
  get 'image_uploader', to: 'pages#image_uploader', as: :image_uploader
  post 'upload_image', to: 'pages#upload_image', as: :upload_image
  get 'image_exists', to: 'pages#image_exists', as: :image_exists
  get 'modal_holder', to: 'pages#modal_holder', as: :modal_holder
  get 'modal_innard', to: 'pages#modal_innard', as: :modal_innard
  get 'pages/awaiting_confirmation', as: :awaiting_confirmation

end

app/models/article.rb
class Article < ActiveRecord::Base
end

app/models/category.rb
class Category < ActiveRecord::Base
  has_many :product_categories, dependent: :destroy
  has_many :products, through: :product_categories

  validates :name, uniqueness: true
end

app/models/collar.rb
class Collar < ActiveRecord::Base
  belongs_to :collarable, polymorphic: true
end

app/models/comment.rb
class Comment < ActiveRecord::Base
  belongs_to :trinket
end

app/models/critter.rb
class Critter < ActiveRecord::Base
  validates_presence_of :description
  has_one :collar, as: :collarable

  default_scope { order(created_at: :asc) }
end

app/models/dog.rb
class Dog < ActiveRecord::Base
  validates_presence_of :description, :name
  has_one :collar, as: :collarable
end

app/models/product.rb
class Product < ActiveRecord::Base
  has_many :product_categories, dependent: :destroy
  has_many :categories, through: :product_categories
end

app/models/product_category.rb
class ProductCategory < ActiveRecord::Base
  belongs_to :product
  belongs_to :category
end

app/models/screening.rb
class Screening < ActiveRecord::Base
end

app/models/trinket.rb
class Trinket < ActiveRecord::Base
  mount_uploader :image, TrinketImageUploader
  has_many :comments

  validate :image_exists

  private

  def image_exists
    if image
      url = "#{ENV['S3_BASE_URL']}#{ENV['S3_BUCKET_NAME']}/#{image.filename}"
      uri = URI(url)
      request = Net::HTTP.new uri.host
      response= request.request_head uri.path
      code = response.code.to_i == 200
    end
  end
end

app/models/user.rb
class User < ActiveRecord::Base

  devise :database_authenticatable, :registerable,
         :recoverable, :rememberable, :trackable, :validatable, :confirmable


  validates :username, :presence => true, :uniqueness => true
  validates_format_of :username, with: /\A[a-zA-Z0-9_\.]*\z/


  extend FriendlyId
  friendly_id :username, :use => :history

  def should_generate_new_friendly_id?
    username_changed?
  end

end

app/models/vendor.rb
class Vendor < ActiveRecord::Base
end

app/controllers/dogs_controller.rb
class DogsController < ApplicationController
  before_action :set_dog, only: [:show, :edit, :update, :destroy]

  # GET /dogs
  # GET /dogs.json
  def index
    @dogs = Dog.all
    @dog = Dog.new
  end

  # GET /dogs/1
  # GET /dogs/1.json
  def show
  end

  # GET /dogs/new
  def new
    @dog = Dog.new
  end

  # GET /dogs/1/edit
  def edit
  end

  # POST /dogs
  # POST /dogs.json
  def create
    @dog = Dog.new(dog_params)

    respond_to do |format|
      if @dog.save
        format.html { redirect_to @dog}
        format.json { render :show, status: :created, location: @dog }
        format.js
      else
        flash.now[:alert] = "Error creating dog: #{@dog.errors.full_messages.join(', ')}"
        format.html { render :new }
        format.json { render json: @dog.errors, status: :unprocessable_entity }
        format.js
      end
    end
  end

  # PATCH/PUT /dogs/1
  # PATCH/PUT /dogs/1.json
  def update
    respond_to do |format|
      if @dog.update(dog_params)
        format.html { redirect_to @dog, notice: 'Dog was successfully updated.' }
        format.json { render :show, status: :ok, location: @dog }
        format.js
      else
        flash.now[:alert] = "Error updating dog: #{@dog.errors.full_messages.join(', ')}"
        format.html { render :edit }
        format.json { render json: @dog.errors, status: :unprocessable_entity }
        format.js
      end
    end
  end

  # DELETE /dogs/1
  # DELETE /dogs/1.json
  def destroy
    @dog.destroy
    respond_to do |format|
      flash.now[:notice] = "Dog successfully destroyed."
      format.html { redirect_to dogs_url}
      format.json { head :no_content }
      format.js
    end
  end

  private
    # Use callbacks to share common setup or constraints between actions.
    def set_dog
      @dog = Dog.find(params[:id])
    end

    # Never trust parameters from the scary internet, only allow the white list through.
    def dog_params
      params.require(:dog).permit(:name, :description)
    end
end

app/helpers/articles_helper.rb
module ArticlesHelper
end

app/helpers/collars_helper.rb
module CollarsHelper
end

app/helpers/comments_helper.rb
module CommentsHelper
end

app/helpers/critters_helper.rb
module CrittersHelper
end

app/helpers/dogs_helper.rb
module DogsHelper
end

app/helpers/pages_helper.rb
module PagesHelper
end

app/helpers/products_helper.rb
module ProductsHelper
end

app/helpers/trinkets_helper.rb
module TrinketsHelper
end

app/helpers/users_helper.rb
module UsersHelper
end

app/helpers/vendors_helper.rb
module VendorsHelper
end

app/views/dogs/_dog_row.html.erb
<tr id="<%= dog.id %>">
  <td><%= dog.name %></td>
  <td><%= dog.description %></td>
  <td><%= link_to 'Show', dog %></td>
  <td><%= link_to 'Edit', edit_dog_path(dog), remote: true %></td>
  <td><%= link_to 'Destroy', dog, method: :delete, remote: true %></td>
</tr>

app/views/dogs/_form.html.erb
<div class="modal fade dog-modal-form" id="dog-form-modal" tabindex="-1" role="dialog">
  <div class="modal-dialog" role="document">
    <div class="modal-content">
      <div class="modal-header">
        <h2>Create New Dog!</h2>
        <button type="button" class="close" data-dismiss="modal" aria-label="Close"><span aria-hidden="true">&times;</span></button>
      </div>
      <div class='modal-body'>
        <%= form_for(@dog, remote: true) do |f| %>
          <div class="field">
            <%= f.text_field :name, class: 'form-control', placeholder: 'Doog Name' %>
          </div>
          <div class="field">
            <%= f.text_field :description, class: 'form-control', placeholder: 'Description' %>
          </div>
        </div>
          <br style="clear:both;">
        <div class="modal-footer">
          <button type="button" class="btn btn-default modal-close-btn" data-dismiss="modal">Cancel</button>
          <%= f.submit "Create Dog", id: 'submit-dog-btn', class: 'btn btn-success' %>
          <% end %>
        </div>
    </div>
  </div>
</div>

app/views/dogs/create.js.erb
var dogTable = $(".dog-table-container table");
$('#dog-form-modal').modal('toggle');
resetDogForm();
<% if alert %>
  $('.alert-msg').removeClass('hidden').text("<%= raw alert %>"); //raw needed to escape characters such as apostrophes
<% else %>
  dogTable.append("<%= j(render partial: 'dogs/dog_row', locals: {:dog => @dog}) %>");
<% end %>

app/views/dogs/destroy.js.erb
$("tr#<%= @dog.id %>").remove();
<% if notice %>
  $('.notice-msg').removeClass('hidden');
  $('.notice-msg').text('<%= notice %>');
<% end %>

app/views/dogs/edit.html.erb
<h1>Editing Dog</h1>

<%= render 'form' %>

<%= link_to 'Show', @dog %> |
<%= link_to 'Back', dogs_path %>

app/views/dogs/edit.js.erb
$('#dog-form-modal').modal('toggle');
$('#dog-form-modal h2').text("Editing <%= @dog.name %>!");
$('form.new_dog #dog_name').val("<%= @dog.name %>");
$('form.new_dog #dog_description').val("<%= @dog.description %>");
$('form.new_dog').attr('action', ("<%= dog_url(@dog.id) %>"));
$('form.new_dog').attr('method', 'patch'); // change method to patch
$('form.new_dog input').first().attr('method', 'put'); // change method to put
$('#submit-dog-btn').attr('value', 'Update Dog'); // change to "update" instead of 'create'

app/views/dogs/index.html.erb
<p class="hidden notice-msg"><%= notice %></p>
<p class="hidden alert-msg"><%= alert %></p>

<h1 id="dog-header">Page of Dogs</h1>

<%= link_to 'New Dog', new_dog_path, remote: true, class: 'btn btn-primary', id: 'new-dog-btn' %>

<div class="dog-table-container">
  <table class="table table-striped">
    <thead>
      <tr>
        <th>Name</th>
        <th>Description</th>
        <th colspan="3">Actions</th>
      </tr>
    </thead>

    <tbody>
      <% @dogs.each do |dog| %>
        <%= render 'dog_row', dog: dog %>
      <% end %>
    </tbody>
  </table>
</div>

<br>

<%= render 'form' %>

app/views/dogs/new.html.erb
<h1>New Dog</h1>

<%= render 'form' %>

<%= link_to 'Back', dogs_path %>

app/views/dogs/new.js.erb
$('#dog-form-modal').modal('toggle');

app/views/dogs/show.html.erb
<p id="notice"><%= notice %></p>

<p>
  <strong>Name:</strong>
  <%= @dog.name %>
</p>

<p>
  <strong>Description:</strong>
  <%= @dog.description %>
</p>

<%= link_to 'Edit', edit_dog_path(@dog) %> |
<%= link_to 'Back', dogs_path %>

app/views/dogs/update.js.erb
var dogRow = $(".dog-table-container table tr#<%= @dog.id %>");
$('#dog-form-modal').modal('toggle');
resetDogForm();
<% if alert %>
  $('.alert-msg').removeClass('hidden').text("<%= raw alert %>"); //raw needed to escape characters such as apostrophes
<% else %>
  dogRow.replaceWith("<%= j(render partial: 'dogs/dog_row', locals: {:dog => @dog}) %>");
<% end %>