config/routes.rb
Rails.application.routes.draw do


  resources :articles
  resources :vendors
  resources :products
  resources :collars
  resources :screenings
  resources :trinkets do
    resources :comments
  end
  resources :dogs
  resources :critters
  devise_for :users, :controllers => {:registrations => "registrations"}

  resources :users, only: [:show], as: :user

  root 'pages#home'
  get 'about', to: 'pages#about', as: :about
  get 'lipsum', to: 'pages#lipsum', as: :lipsum
  get 'scopes', to: 'pages#scopes', as: :scopes
  get 'framer', to: 'pages#framer', as: :framer
  get 'framer2', to: 'pages#framer2', as: :framer2
  get 'context', to: 'pages#context', as: :context
  get 'paver', to: 'pages#paver', as: :paver
  get 'filter', to: 'pages#filter', as: :filter
  get 'gimmie_crits', to: 'pages#gimmie_crits', as: :gimmie_crits
  get 'image_uploader', to: 'pages#image_uploader', as: :image_uploader
  post 'upload_image', to: 'pages#upload_image', as: :upload_image
  get 'image_exists', to: 'pages#image_exists', as: :image_exists
  get 'modal_holder', to: 'pages#modal_holder', as: :modal_holder
  get 'modal_innard', to: 'pages#modal_innard', as: :modal_innard
  get 'pages/awaiting_confirmation', as: :awaiting_confirmation

end

app/models/article.rb
class Article < ActiveRecord::Base
end

app/models/category.rb
class Category < ActiveRecord::Base
  has_many :product_categories, dependent: :destroy
  has_many :products, through: :product_categories

  validates :name, uniqueness: true
end

app/models/collar.rb
class Collar < ActiveRecord::Base
  belongs_to :collarable, polymorphic: true
end

app/models/comment.rb
class Comment < ActiveRecord::Base
  belongs_to :trinket
end

app/models/critter.rb
class Critter < ActiveRecord::Base
  validates_presence_of :description
  has_one :collar, as: :collarable

  default_scope { order(created_at: :asc) }
end

app/models/dog.rb
class Dog < ActiveRecord::Base
  validates_presence_of :description, :name
  has_one :collar, as: :collarable
end

app/models/product.rb
class Product < ActiveRecord::Base
  has_many :product_categories, dependent: :destroy
  has_many :categories, through: :product_categories
end

app/models/product_category.rb
class ProductCategory < ActiveRecord::Base
  belongs_to :product
  belongs_to :category
end

app/models/screening.rb
class Screening < ActiveRecord::Base
end

app/models/trinket.rb
class Trinket < ActiveRecord::Base
  mount_uploader :image, TrinketImageUploader
  has_many :comments

  validate :image_exists

  private

  def image_exists
    if image
      url = "#{ENV['S3_BASE_URL']}#{ENV['S3_BUCKET_NAME']}/#{image.filename}"
      uri = URI(url)
      request = Net::HTTP.new uri.host
      response= request.request_head uri.path
      code = response.code.to_i == 200
    end
  end
end

app/models/user.rb
class User < ActiveRecord::Base

  devise :database_authenticatable, :registerable,
         :recoverable, :rememberable, :trackable, :validatable, :confirmable


  validates :username, :presence => true, :uniqueness => true
  validates_format_of :username, with: /\A[a-zA-Z0-9_\.]*\z/


  extend FriendlyId
  friendly_id :username, :use => :history

  def should_generate_new_friendly_id?
    username_changed?
  end

end

app/models/vendor.rb
class Vendor < ActiveRecord::Base
end

app/controllers/trinkets_controller.rb
class TrinketsController < ApplicationController
  before_action :set_trinket, only: [:show, :edit, :update, :destroy]

  # GET /trinkets
  # GET /trinkets.json
  def index
    @trinkets = Trinket.all
  end

  # GET /trinkets/1
  # GET /trinkets/1.json
  def show
  end

  # GET /trinkets/new
  def new
    @trinket = Trinket.new
  end

  # GET /trinkets/1/edit
  def edit
  end

  # POST /trinkets
  # POST /trinkets.json
  def create
    @trinket = Trinket.new(trinket_params)

    respond_to do |format|
      if @trinket.save
        format.html { redirect_to @trinket, notice: 'Trinket was successfully created.' }
        format.json { render :show, status: :created, location: @trinket }
      else
        format.html { render :new }
        format.json { render json: @trinket.errors, status: :unprocessable_entity }
      end
    end
  end

  # PATCH/PUT /trinkets/1
  # PATCH/PUT /trinkets/1.json
  def update
    respond_to do |format|
      if @trinket.update(trinket_params)
        format.html { redirect_to @trinket, notice: 'Trinket was successfully updated.' }
        format.json { render :show, status: :ok, location: @trinket }
      else
        format.html { render :edit }
        format.json { render json: @trinket.errors, status: :unprocessable_entity }
      end
    end
  end

  # DELETE /trinkets/1
  # DELETE /trinkets/1.json
  def destroy
    @trinket.destroy
    respond_to do |format|
      format.html { redirect_to trinkets_url, notice: 'Trinket was successfully destroyed.' }
      format.json { head :no_content }
    end
  end

  private
    # Use callbacks to share common setup or constraints between actions.
    def set_trinket
      @trinket = Trinket.find(params[:id])
    end

    # Never trust parameters from the scary internet, only allow the white list through.
    def trinket_params
      params.require(:trinket).permit(:name, :description, :image)
    end
end

app/helpers/articles_helper.rb
module ArticlesHelper
end

app/helpers/collars_helper.rb
module CollarsHelper
end

app/helpers/comments_helper.rb
module CommentsHelper
end

app/helpers/critters_helper.rb
module CrittersHelper
end

app/helpers/dogs_helper.rb
module DogsHelper
end

app/helpers/pages_helper.rb
module PagesHelper
end

app/helpers/products_helper.rb
module ProductsHelper
end

app/helpers/trinkets_helper.rb
module TrinketsHelper
end

app/helpers/users_helper.rb
module UsersHelper
end

app/helpers/vendors_helper.rb
module VendorsHelper
end

app/views/trinkets/_edit_trinket_modal.html.erb
<div class="modal fade trinket-modal-form" id="trinket-form-modal" tabindex="-1" role="dialog">
  <div class="modal-dialog" role="document">
    <div class="modal-content">
      <div class="modal-header">
        <span class="modal-title">Create New Trinket!</span>
        <button type="button" class="close" data-dismiss="modal" aria-label="Close"><span aria-hidden="true">&times;</span></button>
      </div>
      <div class='modal-body'>
        <%= form_for(@trinket, remote: true) do |f| %>
          <div class="field">
            <%= f.label :name %>
            <%= f.text_field :name, class: 'form-control', placeholder: 'Trinket Name' %>
          </div>
          <div class="field">
            <%= f.label :description %>
            <%= f.text_field :description, class: 'form-control', placeholder: 'Description' %>
          </div>
        </div>
          <br style="clear:both;">
        <div class="modal-footer">
          <button type="button" class="btn btn-default modal-close-btn" data-dismiss="modal">Cancel</button>
          <%= f.submit "Create Trinket", id: 'submit-trinket-btn', class: 'btn btn-success' %>
          <% end %>
        </div>
    </div>
  </div>
</div>

app/views/trinkets/_form.html.erb
<%= form_for @trinket, html: {multipart: true} do |f| %>
  <% if @trinket.errors.any? %>
    <div id="error_explanation">
      <h2><%= pluralize(@trinket.errors.count, "error") %> prohibited this trinket from being saved:</h2>

      <ul>
      <% @trinket.errors.full_messages.each do |message| %>
        <li><%= message %></li>
      <% end %>
      </ul>
    </div>
  <% end %>

  <div class="field">
    <%= f.label :name %><br>
    <%= f.text_field :name %>
  </div>
  <div class="field">
    <%= f.label :description %><br>
    <%= f.text_field :description %>
  </div>
  <div class="field">
    <%= f.label :image %><br>
    <%= f.file_field :image %>
  </div>
  <div class="actions">
    <%= f.submit %>
  </div>
<% end %>

app/views/trinkets/edit.html.erb
<h1>Editing Trinket</h1>

<%= render 'edit_trinket_modal' %>

<%= link_to 'Edit Trinket', '', data: {toggle: 'modal', target: '#trinket-form-modal'} %>

<div class="bottom-links">
  <%= link_to 'Show', @trinket %> |
  <%= link_to 'Back', trinkets_path %>
</div>

app/views/trinkets/index.html.erb
<p id="notice"><%= notice %></p>

<h1>Listing Trinkets</h1>

<table class='table'>
  <thead>
    <tr>
      <th>Name</th>
      <th>Description</th>
      <th colspan="3"></th>
    </tr>
  </thead>

  <tbody>
    <% @trinkets.each do |trinket| %>
      <tr>
        <td><%= trinket.name %></td>
        <td><%= trinket.description %></td>
        <td><%= link_to 'Show', trinket, class: 'btn btn-default btn-xs' %></td>
        <td><%= link_to 'Edit', edit_trinket_path(trinket), class: 'btn btn-default btn-xs' %></td>
        <td><%= link_to 'Destroy', trinket, method: :delete, data: { confirm: 'Are you sure?' }, class: 'btn btn-default btn-xs' %></td>
      </tr>
    <% end %>
  </tbody>
</table>

<br>

<%= link_to 'New Trinket', new_trinket_path %>

app/views/trinkets/new.html.erb
<h1>New Trinket</h1>

<%= render 'form' %>

<%= link_to 'Back', trinkets_path %>

app/views/trinkets/show.html.erb
<p id="notice"><%= notice %></p>

<p>
  <strong>Name:</strong>
  <%= @trinket.name %>
</p>

<p>
  <strong>Description:</strong>
  <%= @trinket.description %>
</p>

<p>
  <strong>Image:</strong>
  <%= image_tag @trinket.image_url %>
</p>

<%= link_to 'Edit', edit_trinket_path(@trinket) %> |
<%= link_to 'Back', trinkets_path %>

<h1>Listing comments</h1>

<table>
  <tr>
    <th>Name</th>
    <th>Content</th>
    <th></th>
    <th></th>
    <th></th>
  </tr>

<% @trinket.comments.each do |comment| %>
  <tr>
    <td><%= comment.name %></td>
    <td><%= comment.content %></td>
    <td><%= link_to 'Show', [comment.trinket, comment] %></td>
    <td><%= link_to 'Edit', edit_trinket_comment_path(comment.trinket, comment) %></td>
    <td><%= link_to 'Destroy', [comment.trinket, comment], :confirm => 'Are you sure?', :method => :delete %></td>
  </tr>
<% end %>
</table>

<br />

<%= link_to 'New Comment', new_trinket_comment_path(@trinket) %>