config/routes.rb
Rails.application.routes.draw do


  resources :articles
  resources :vendors
  resources :products
  resources :collars
  resources :screenings
  resources :trinkets do
    resources :comments
  end
  resources :dogs
  resources :critters
  devise_for :users, :controllers => {:registrations => "registrations"}

  resources :users, only: [:show], as: :user

  root 'pages#home'
  get 'about', to: 'pages#about', as: :about
  get 'lipsum', to: 'pages#lipsum', as: :lipsum
  get 'scopes', to: 'pages#scopes', as: :scopes
  get 'framer', to: 'pages#framer', as: :framer
  get 'framer2', to: 'pages#framer2', as: :framer2
  get 'context', to: 'pages#context', as: :context
  get 'paver', to: 'pages#paver', as: :paver
  get 'filter', to: 'pages#filter', as: :filter
  get 'gimmie_crits', to: 'pages#gimmie_crits', as: :gimmie_crits
  get 'image_uploader', to: 'pages#image_uploader', as: :image_uploader
  post 'upload_image', to: 'pages#upload_image', as: :upload_image
  get 'image_exists', to: 'pages#image_exists', as: :image_exists
  get 'modal_holder', to: 'pages#modal_holder', as: :modal_holder
  get 'modal_innard', to: 'pages#modal_innard', as: :modal_innard
  get 'pages/awaiting_confirmation', as: :awaiting_confirmation

end

app/models/article.rb
class Article < ActiveRecord::Base
end

app/models/category.rb
class Category < ActiveRecord::Base
  has_many :product_categories, dependent: :destroy
  has_many :products, through: :product_categories

  validates :name, uniqueness: true
end

app/models/collar.rb
class Collar < ActiveRecord::Base
  belongs_to :collarable, polymorphic: true
end

app/models/comment.rb
class Comment < ActiveRecord::Base
  belongs_to :trinket
end

app/models/critter.rb
class Critter < ActiveRecord::Base
  validates_presence_of :description
  has_one :collar, as: :collarable

  default_scope { order(created_at: :asc) }
end

app/models/dog.rb
class Dog < ActiveRecord::Base
  validates_presence_of :description, :name
  has_one :collar, as: :collarable
end

app/models/product.rb
class Product < ActiveRecord::Base
  has_many :product_categories, dependent: :destroy
  has_many :categories, through: :product_categories
end

app/models/product_category.rb
class ProductCategory < ActiveRecord::Base
  belongs_to :product
  belongs_to :category
end

app/models/screening.rb
class Screening < ActiveRecord::Base
end

app/models/trinket.rb
class Trinket < ActiveRecord::Base
  mount_uploader :image, TrinketImageUploader
  has_many :comments

  validate :image_exists

  private

  def image_exists
    if image
      url = "#{ENV['S3_BASE_URL']}#{ENV['S3_BUCKET_NAME']}/#{image.filename}"
      uri = URI(url)
      request = Net::HTTP.new uri.host
      response= request.request_head uri.path
      code = response.code.to_i == 200
    end
  end
end

app/models/user.rb
class User < ActiveRecord::Base

  devise :database_authenticatable, :registerable,
         :recoverable, :rememberable, :trackable, :validatable, :confirmable


  validates :username, :presence => true, :uniqueness => true
  validates_format_of :username, with: /\A[a-zA-Z0-9_\.]*\z/


  extend FriendlyId
  friendly_id :username, :use => :history

  def should_generate_new_friendly_id?
    username_changed?
  end

end

app/models/vendor.rb
class Vendor < ActiveRecord::Base
end

app/controllers/vendors_controller.rb
class VendorsController < ApplicationController
  before_action :set_vendor, only: [:show, :edit, :update, :destroy]

  # GET /vendors
  # GET /vendors.json
  def index
    @vendors = Vendor.all
  end

  # GET /vendors/1
  # GET /vendors/1.json
  def show
  end

  # GET /vendors/new
  def new
    @vendor = Vendor.new
  end

  # GET /vendors/1/edit
  def edit
  end

  # POST /vendors
  # POST /vendors.json
  def create
    @vendor = Vendor.new(vendor_params)

    respond_to do |format|
      if @vendor.save
        format.html { redirect_to @vendor, notice: 'Vendor was successfully created.' }
        format.json { render :show, status: :created, location: @vendor }
      else
        format.html { render :new }
        format.json { render json: @vendor.errors, status: :unprocessable_entity }
      end
    end
  end

  # PATCH/PUT /vendors/1
  # PATCH/PUT /vendors/1.json
  def update
    respond_to do |format|
      if @vendor.update(vendor_params)
        format.html { redirect_to @vendor, notice: 'Vendor was successfully updated.' }
        format.json { render :show, status: :ok, location: @vendor }
      else
        format.html { render :edit }
        format.json { render json: @vendor.errors, status: :unprocessable_entity }
      end
    end
  end

  # DELETE /vendors/1
  # DELETE /vendors/1.json
  def destroy
    @vendor.destroy
    respond_to do |format|
      format.html { redirect_to vendors_url, notice: 'Vendor was successfully destroyed.' }
      format.json { head :no_content }
    end
  end

  private
    # Use callbacks to share common setup or constraints between actions.
    def set_vendor
      @vendor = Vendor.find(params[:id])
    end

    # Never trust parameters from the scary internet, only allow the white list through.
    def vendor_params
      params.require(:vendor).permit(:name, :description)
    end
end

app/helpers/articles_helper.rb
module ArticlesHelper
end

app/helpers/collars_helper.rb
module CollarsHelper
end

app/helpers/comments_helper.rb
module CommentsHelper
end

app/helpers/critters_helper.rb
module CrittersHelper
end

app/helpers/dogs_helper.rb
module DogsHelper
end

app/helpers/pages_helper.rb
module PagesHelper
end

app/helpers/products_helper.rb
module ProductsHelper
end

app/helpers/trinkets_helper.rb
module TrinketsHelper
end

app/helpers/users_helper.rb
module UsersHelper
end

app/helpers/vendors_helper.rb
module VendorsHelper
end

app/views/vendors/_form.html.erb
<%= form_for(@vendor) do |f| %>
  <% if @vendor.errors.any? %>
    <div id="error_explanation">
      <h2><%= pluralize(@vendor.errors.count, "error") %> prohibited this vendor from being saved:</h2>

      <ul>
      <% @vendor.errors.full_messages.each do |message| %>
        <li><%= message %></li>
      <% end %>
      </ul>
    </div>
  <% end %>

  <div class="field">
    <%= f.label :name %><br>
    <%= f.text_field :name %>
  </div>
  <div class="field">
    <%= f.label :description %><br>
    <%= f.text_area :description %>
  </div>
  <div class="actions">
    <%= f.submit %>
  </div>
<% end %>

app/views/vendors/edit.html.erb
<h1>Editing Vendor</h1>

<%= render 'form' %>

<%= link_to 'Show', @vendor %> |
<%= link_to 'Back', vendors_path %>

app/views/vendors/index.html.erb
<p id="notice"><%= notice %></p>

<h1>Listing Vendors</h1>

<table>
  <thead>
    <tr>
      <th>Name</th>
      <th>Description</th>
      <th colspan="3"></th>
    </tr>
  </thead>

  <tbody>
    <% @vendors.each do |vendor| %>
      <tr>
        <td><%= vendor.name %></td>
        <td><%= vendor.description %></td>
        <td><%= link_to 'Show', vendor %></td>
        <td><%= link_to 'Edit', edit_vendor_path(vendor) %></td>
        <td><%= link_to 'Destroy', vendor, method: :delete, data: { confirm: 'Are you sure?' } %></td>
      </tr>
    <% end %>
  </tbody>
</table>

<br>

<%= link_to 'New Vendor', new_vendor_path %>

app/views/vendors/new.html.erb
<h1>New Vendor</h1>

<%= render 'form' %>

<%= link_to 'Back', vendors_path %>

app/views/vendors/show.html.erb
<p id="notice"><%= notice %></p>

<p>
  <strong>Name:</strong>
  <%= @vendor.name %>
</p>

<p>
  <strong>Description:</strong>
  <%= @vendor.description %>
</p>

<%= link_to 'Edit', edit_vendor_path(@vendor) %> |
<%= link_to 'Back', vendors_path %>